services:
  - type: web
    name: nba-game-simulator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn basketball_simulator_agency.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: DATABASE_URL
        fromDatabase:
          name: nba-simulator-db
          property: connectionString
      - key: RENDER
        value: true

databases:
  - name: nba-simulator-db
    databaseName: basketball_sim
    ipAllowList: []  # optional (allows all)
    plan: free 